version: "3.8"

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - USER=admin
      - PASSWORD=99999999
      - SECRET=4715aed3216f7b0a38e6b534a958362654e96d10fbc04700770d572af3dce43625dd
      - APIKEY=5saedXklbslhnapihe2pihp3pih4fdnakhjwq5
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
    volumes:
      - ./data:/app/data
    command: "sh -c `chown -R 1001:1001 /app/data`"
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: G6r#T@1zU*^j
      MYSQL_DATABASE: serpbear
      MYSQL_USER: serpbear
      MYSQL_PASSWORD: 8TxnsEr&EusL
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
networks:
  my-network:
    driver: bridge
volumes:
  serpbear_appdata:
  db_data: